# Generated by Django 4.2.1 on 2023-05-25 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_mst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product_sub_cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_prize', models.IntegerField()),
                ('Product_img', models.FileField(default='flower.jpg', upload_to='product_images')),
                ('Product_model', models.CharField(max_length=150)),
                ('Product_ram', models.CharField(max_length=50)),
                ('Product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product_mst')),
            ],
        ),
    ]
